### ISSUE TITLE
Wikidata property and qualifier overwrite themselves

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/PyGenericSpreadSheet#10]
propByName is based on the aggregated result of mapDict.
Thus, properties with different name but same proeprtyId (qualifier with same id but different name) overwrite them selves so that only one property stays in mapDict and either the property or the qualifiers are removed.

https://github.com/WolfgangFahl/PyGenericSpreadSheet/blob/fcbe0b97a71655e88710f602a5cb60ae6784ba8f/spreadsheet/wikidata.py#L157

```
mapDict(dict): the mapping dictionary to use
```
expected parameter needs to be adjusted to allow qualifiers and properties with the same PropertyId

**Comment by WolfgangFahl** [comment]
if this is still a problem readd to https://pypi.org/project/py-ez-wikidata/
