### ISSUE TITLE
wikidata import - improve error handing when label or description is not set

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/PyGenericSpreadSheet#11]
https://github.com/WolfgangFahl/PyGenericSpreadSheet/blob/fcbe0b97a71655e88710f602a5cb60ae6784ba8f/spreadsheet/wikidata.py#L219

https://github.com/WolfgangFahl/PyGenericSpreadSheet/blob/fcbe0b97a71655e88710f602a5cb60ae6784ba8f/spreadsheet/wikidata.py#L220

**Comment by WolfgangFahl** [comment]
Yes that's possible and annoying. So far my workaround was to change the wikidata item that caused the problem manually.

**Comment by WolfgangFahl** [comment]
if this is still a problem readd to https://pypi.org/project/py-ez-wikidata/
