### ISSUE TITLE
WikibaseQuery use wbtn prefix to query extid url

### ISSUE THREAD

**Issue by tholzheim** [WolfgangFahl/PyGenericSpreadSheet#15]
Instead of :
```SPARQL
?item wdt:P496 ?ORCID_iD.
    wd:P496 wdt:P1630 ?ORCID_iDFormatterUrl.
    BIND(IRI(REPLACE(?ORCID_iD, '^(.+)$', ?ORCID_iDFormatterUrl)) AS ?ORCID_iDUrl).
```
we could use 
```SPARQL
?item wdt:P496 ?ORCID_iD.
?item wdtn:P496 ?ORCID_iDUrl.
```

Only thing we need to ensure that for the extid property the  [formatter URI for RDF resource (P1921)](https://www.wikidata.org/wiki/Special:EntityPage/P1921) is set.
I currently do not know how long it takes until the property with `wdtn:` prefix is available. (Added the property now to [google scholar author id](https://www.wikidata.org/wiki/Property:P1960) so we will see)
But it will improve the query execution time since the string operations are removed and it will also allow to use the query on Qlever

>If the property has a formatter URI for RDF configured (on Wikidata: [formatter URI for RDF resource (P1921)](https://www.wikidata.org/wiki/Special:EntityPage/P1921)), the RDF will also have normalized value, e.g.:
>```turtle
> wd:Q123 wdt:P234 "External-ID" ; 
>         wdtn:P234 <http://external.example.com/reference/External-ID>.
>```
> see https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format#External_Id

**Comment by WolfgangFahl** [comment]
moved to py_ez_wikidata
